/**
 * Memory Loop Shared Types and Protocols
 *
 * Zod schemas for protocol validation, TypeScript types for Vault/Session/Message
 * models, and shared utilities for frontend and backend.
 */

export const VERSION = "0.1.0";

export type {
  VaultInfo,
  SessionMetadata,
  ErrorCode,
  StoredToolInvocation,
  ConversationMessage,
  Badge,
  BadgeColor,
  SaveConfigResult,
} from "./types";

export type { EditableVaultConfig } from "./protocol";
export { EditableVaultConfigSchema, EditableBadgeSchema } from "./protocol";

export {
  VaultInfoSchema,
  ErrorCodeSchema,
  FileEntrySchema,
  TaskCategorySchema,
  TaskEntrySchema,
  RecentNoteEntrySchema,
  RecentDiscussionEntrySchema,
  ToolInvocationSchema,
  ConversationMessageSchema,
  InspirationItemSchema,
  SlashCommandSchema,
  FileSearchResultSchema,
  ContentSearchResultSchema,
  ContextSnippetSchema,
  MeetingStateSchema,
  ReviewResponseSchema,
  DueCardSchema,
  CardDetailSchema,
  ReviewRequestSchema,
  ReviewResultSchema,
  ArchiveResponseSchema,
  DueCardsResponseSchema,
  // Client -> Server (WebSocket)
  SelectVaultMessageSchema,
  CreateVaultMessageSchema,
  DiscussionMessageSchema,
  ResumeSessionMessageSchema,
  NewSessionMessageSchema,
  AbortMessageSchema,
  PingMessageSchema,
  ClientMessageSchema,
  // Server -> Client (WebSocket)
  VaultListMessageSchema,
  VaultCreatedMessageSchema,
  SessionReadyMessageSchema,
  ResponseStartMessageSchema,
  ResponseChunkMessageSchema,
  ResponseEndMessageSchema,
  ToolStartMessageSchema,
  ToolInputMessageSchema,
  ToolEndMessageSchema,
  ErrorMessageSchema,
  PongMessageSchema,
  ServerMessageSchema,
  parseClientMessage,
  parseServerMessage,
  safeParseClientMessage,
  safeParseServerMessage,
} from "./protocol";

export type {
  ConversationMessageProtocol,
  FileEntry,
  TaskCategory,
  TaskEntry,
  RecentNoteEntry,
  RecentDiscussionEntry,
  ToolInvocation,
  InspirationItem,
  SlashCommand,
  FileSearchResult,
  ContentSearchResult,
  ContextSnippet,
  MeetingState,
  ReviewResponse,
  DueCard,
  CardDetail,
  ReviewRequest,
  ReviewResult,
  ArchiveResponse,
  DueCardsResponse,
  AskUserQuestionOption,
  AskUserQuestionItem,
  AskUserQuestionResponseMessage,
  AskUserQuestionRequestMessage,
  QuickActionType,
  QuickActionRequestMessage,
  AdvisoryActionType,
  AdvisoryActionRequestMessage,
  // Client messages (WebSocket)
  SelectVaultMessage,
  CreateVaultMessage,
  DiscussionMessage,
  ResumeSessionMessage,
  NewSessionMessage,
  AbortMessage,
  PingMessage,
  ClientMessage,
  // Server messages (WebSocket)
  VaultListMessage,
  VaultCreatedMessage,
  SessionReadyMessage,
  ResponseStartMessage,
  ResponseChunkMessage,
  ResponseEndMessage,
  ToolStartMessage,
  ToolInputMessage,
  ToolEndMessage,
  ErrorMessage,
  PongMessage,
  ServerMessage,
} from "./protocol";
